apiVersion: v1
kind: Service
metadata:
  name: warehouse-metrics-service
spec:
  type: NodePort
  selector:
    app: warehouse-metrics
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30003