apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-metrics
  labels:
    app: warehouse-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-metrics
  template:
    metadata:
      labels:
        app: warehouse-metrics
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: warehouse-metrics
          image: kamal578/warehouse-metrics:0.0.1
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: warehouse
            - name: PORT
              value: '3000'
            - name: NODE_ENV
              value: production
          volumeMounts:
            - name: logs-volume
              mountPath: /usr/src/app/logs
      volumes:
        - name: logs-volume
          emptyDir: {}
