apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DATABASE_URL: postgres://postgres:admin@postgres:5432/warehouse
  POSTGRES_HOST: postgres
  POSTGRES_PORT: '5432'
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: warehouse
  PORT: '3000'
  NODE_ENV: production