apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-metrics
  labels:
    app: warehouse-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-metrics
  template:
    metadata:
      labels:
        app: warehouse-metrics
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: warehouse-metrics
          image: kamal578/warehouse-metrics:0.0.1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: logs-volume
              mountPath: /usr/src/app/logs
      volumes:
        - name: logs-volume
          emptyDir: {}
