apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  labels:
    app: prometheus
data:
  alerts.yml: |
    groups:
    - name: warehouse-metrics-rules
      rules:
      - alert: HighHTTP500ErrorRate
        expr: sum(rate(http_500_error_count[2m])) > 40
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High HTTP 500 Error Rate"
          description: "The rate of HTTP 500 errors has exceeded 100 in the last 1 minute."
