version: '3.9'
services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: warehouse
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  warehouse:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/warehouse
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: warehouse
      PORT: 3000
      NODE_ENV: production
    entrypoint: ["sh", "app-start.sh"]
    ports:
      - '3000:3000'
    volumes:
      - ./logs:/usr/src/app/logs
      - ./db/migrations:/usr/src/app/db/migrations
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
