version: '3.9'
services:
  postgres:
    image: postgres:16.2-alpine3.18
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  warehouse:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: ["sh", "app-start.sh"]
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./logs:/usr/src/app/logs
      - ./db/migrations:/usr/src/app/db/migrations
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
