version: '3.9'
services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_DB: warehouse
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  warehouse:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/warehouse
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_DB: warehouse
      PORT: 3000
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - postgres

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/warehouse
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_DB: warehouse
      NODE_ENV: production
    depends_on:
      - postgres
    command: npm run migration:run

volumes:
  postgres_data:
