groups:
  - name: warehouse-alerts
    rules:
      - alert: HighHttp500ErrorRate
        expr: sum(rate(http_500_error_count[2m])) > 40
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High HTTP 500 Error Rate"
          description: "HTTP 500 errors are above the threshold of 40 requests per minute."